---
name: Test and formatting

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:

    lint:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
        -   name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version: 3.12
        -   name: Install dependencies
            run: |
                python -m pip install --upgrade pip tox
        -   name: Run checks via precommit and tox
            run: tox

    build:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest] # MacOS fails to run at all # windows-latest: does not work because antspyx is not available for windows
                python-version: ['3.9', '3.10', '3.11']
        runs-on: ${{ matrix.os }}
        steps:
        -   uses: actions/checkout@v4
        -   name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v5
            with:
                python-version: ${{ matrix.python-version }}
        -   name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install .[test]
        -   name: Test with pytest
            run: python -m pytest
